//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhavyaModhiya_490_Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int transactionID { get; set; }
        public Nullable<int> walletID { get; set; }
        public Nullable<decimal> transactionAmount { get; set; }
        public string transactionType { get; set; }
        public Nullable<System.DateTime> transactionTime { get; set; }
        public Nullable<decimal> closingAmount { get; set; }
    
        public virtual Wallet Wallet { get; set; }
    }
}
